// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EndSession(arg1) {
  return window['go']['main']['App']['EndSession'](arg1);
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetLatestScreenshot() {
  return window['go']['main']['App']['GetLatestScreenshot']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetProblem(arg1) {
  return window['go']['main']['App']['GetProblem'](arg1);
}

export function GetSessionTranscript(arg1) {
  return window['go']['main']['App']['GetSessionTranscript'](arg1);
}

export function ListProblems() {
  return window['go']['main']['App']['ListProblems']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2);
}

export function StartCapture(arg1) {
  return window['go']['main']['App']['StartCapture'](arg1);
}

export function StartSession(arg1, arg2) {
  return window['go']['main']['App']['StartSession'](arg1, arg2);
}

export function StopCapture() {
  return window['go']['main']['App']['StopCapture']();
}

export function UpdatePreferences(arg1) {
  return window['go']['main']['App']['UpdatePreferences'](arg1);
}
