// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function EndSession(arg1:string):Promise<void>;

export function GetAuthStatus():Promise<models.AuthStatus>;

export function GetLatestScreenshot():Promise<string>;

export function GetPreferences():Promise<models.Preferences>;

export function GetProblem(arg1:string):Promise<models.Problem>;

export function GetSessionTranscript(arg1:string):Promise<Array<models.Message>>;

export function ListProblems():Promise<Array<models.Problem>>;

export function ListSessions():Promise<Array<models.SessionSummary>>;

export function SendMessage(arg1:string):Promise<string>;

export function SetAPIKey(arg1:string,arg2:string):Promise<void>;

export function StartCapture(arg1:number):Promise<void>;

export function StartSession(arg1:string,arg2:string):Promise<models.Session>;

export function StopCapture():Promise<void>;

export function UpdatePreferences(arg1:models.Preferences):Promise<void>;
